### ISSUE TITLE
Exception after Ellipsoid Fitting in headless mode

### ISSUE THREAD

**Issue by maierl** [mcib3d/mcib3d-plugins#9]
when I call the Ellipsoid Fitting via the console with options `--headless --console -macro`, I get an HeadlessException from [Ellipsoids_3D.java:198](https://github.com/mcib3d/mcib3d-plugins/blob/master/src/main/java/mcib_plugins/Ellipsoids_3D.java#L198)

```
ResultsTable.show(): the system ResultTable should only be displayed in the "Results" window.
java.awt.HeadlessException
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at ij.text.TextWindow.<init>(TextWindow.java:52)
        at ij.text.TextWindow.<init>(TextWindow.java:40)
        at ij.measure.ResultsTable.show(ResultsTable.java:829)
        at mcib_plugins.Ellipsoids_3D.run(Ellipsoids_3D.java:198)
```

**Comment by mcib3d** [comment]
hi,

Actually I do not know how to check if ImageJ is running in headless mode or not. But I can change the name of the results table.

**Comment by maierl** [comment]
Hi, thanks for your quick reply!
After a quick search I didn't find a way to check for headless mode either, but naming the window "Results" instead of "Ellipsoid" avoids the Exception.

**Comment by mcib3d** [comment]
Hi,
Ok, the pull request is done in d7c91536bc0d998e76c152b7dd8eb034e4c8b8fc .
Thanks
